apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-analyzer
  template:
    metadata:
      labels:
        app: resume-analyzer
    spec:
      containers:
      - name: resume-analyzer
        image: ai-resume-analyzer:latest  # This placeholder will be replaced by the pipeline
        imagePullPolicy: Always # Kubernetes will always pull the latest image from ECR
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: GOOGLE_API_KEY
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        # Health checks to ensure the application is ready and healthy
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: resume-analyzer
spec:
  selector:
    app: resume-analyzer
  ports:
  - port: 8000         # The service's exposed port
    targetPort: 8000   # The container port to forward traffic to
    protocol: TCP