name: CI/CD Pipeline for FastAPI on AWS EKS

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

# Set permissions for the job, crucial for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  # Environment variables accessible to all steps in the job
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
  EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: ECR image cleanup
        run: |
          echo "Starting ECR image cleanup..."
          # Get all image digests that do not have the 'latest' tag
          images_to_delete=$(aws ecr describe-images --repository-name $ECR_REPOSITORY \
            --query 'imageDetails[?!(contains(imageTags, `latest`))].imageDigest' \
            --output text)
          
          if [ -n "$images_to_delete" ]; then
            echo "Images to delete: $images_to_delete"
            # Loop through each image digest and delete it.
            # The '|| true' prevents the workflow from failing if an image is already gone.
            for digest in $images_to_delete; do
              aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageDigest=$digest || true
            done
            echo "Cleanup complete."
          else
            echo "No images to clean up."
          fi
      
      - name: Configure Kubernetes client
        run: | 
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }} 

      - name: Create or update Kubernetes secret
        run: |
          kubectl create secret generic fastapi-secrets --from-literal=GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}  --dry-run=client -o yaml | kubectl apply -f - 
      
      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          FULL_IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:latest"
          echo "Updating deployment file with image: $FULL_IMAGE_URI"
          # Use 'sed' to update the deployment file with the new image tag
          sed -i "s|maliktalha27/ai-resume-analyzer|$FULL_IMAGE_URI|g" deployment.yaml

          # Restart the deployment in order to apply the latest image built in this workflow
          # The following command RESTARTS all the deployments in the cluster
          kubectl rollout restart deploy
          # To restart only specific deployments, use the following
          # kubectl rollout restart deployment <deployment name>